spring:
 global-message: Welcome to customer service dev environment
server:
 port : 8084
message: Hello from Dev order service
spring:
 datasource: 
  url: jdbc:mysql://localhost:3306/order-dev
  username: root
  password: root
jpa:
 hibenate:
  ddl-auto : update
  show-sql: true
