spring:
 global-message: Welcome to order service prod environment
 datasource: 
  url: jdbc:mysql://localhost:3306/order-prod
  username: root
  password: root
jpa:
 hibenate:
  ddl-auto : update
  show-sql: true
server:
 port : 8085
message: Hello from prod order service
